
var items = [
    {
        "q": 1,
        "desc": "It is very important to her/him to help people around her/him. She/he wants to care for other people.",
        "subscale": "benevolence",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 2,
        "desc": "It is important to her/him to be loyal to her/his friends. She/he wants to devote herself/himself to people close to her/him.",
        "subscale": "benevolence",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 3,
        "desc": "She/he think it is important that every person in the world be treated equally. She/he wants justice for everybody, even for people She/he don't know.",
        "subscale": "universalism",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 4,
        "desc": "It is important to her/him to listen to people who are different from her/him. Even when she/he disagrees with them, she/he still wants to understand them.",
        "subscale": "universalism",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 5,
        "desc": "She/he strongly believes that people should care for nature. Looking after the environment is important to her/him.",
        "subscale": "universalism",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 6,
        "desc": "Thinking up new ideas and being creative is important to her/him. She/he likes to do things in her/his own original way.",
        "subscale": "self-direction",
        "subscale2": "individualism-independence",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 7,
        "desc": "It is important to her/him to make her/his own decisions about what She/he do. She/he likes to be free and not depend on others.",
        "subscale": "self-direction",
        "subscale2": "individualism-independence",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 8,
        "desc": "She/he likes surprises and is always looking for new things to do. She/he thinks it is important to do lots of different things in life.",
        "subscale": "stimulation",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 9,
        "desc": "She/he looks for adventures and likes to take risks. She/he wants to have an exciting life.",
        "subscale": "stimulation",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 10,
        "desc": "Having a good time is important to her/him. She/he likes to \"spoil\" herself/himself.",
        "subscale": "hedonism",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 11,
        "desc": "She/he seeks every chance she/he can to have fun. It is important to her/him to do things that give her/him pleasure.",
        "subscale": "hedonism",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 12,
        "desc": "It is very important to her/him to show her/his abilities. She/he wants people to admire what she/he do.",
        "subscale": "achievement",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 13,
        "desc": "Being very successful is important to her/him. She/he likes to impress other people.",
        "subscale": "achievement",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 14,
        "desc": "It is important to her/him to be rich. She/he wants to have a lot of money and expensive things.",
        "subscale": "power",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 15,
        "desc": "It is important to her/him to be in charge and tell others what to do. She/he wants people to do what she/he says.",
        "subscale": "power",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 16,
        "desc": "It is important to her/him to live in secure surroundings. She/he avoids anything that might endanger her/his safety.",
        "subscale": "security",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 17,
        "desc": "It is very important to her/him that her/his country be safe from threats from within and without. She/he is concerned that social order be protected.",
        "subscale": "security",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 18,
        "desc": "She/he believe that people should do what they're told. She/he think people should follow rules at all tiher/hims, even when no-one is watching.",
        "subscale": "conformity-obedience",
        "subscale2": "conformity-obedience",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 19,
        "desc": "It is important to her/him always to behave properly. She/he want to avoid doing anything people would say is wrong.",
        "subscale": "conformity-obedience",
        "subscale2": "conformity-obedience",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 20,
        "desc": "It is important to her/him to be humble and modest. She/he try not to draw attention to herself/himself.",
        "subscale": "conformity-obedience",
        "subscale2": "conformity-obedience",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 21,
        "desc": "Tradition is important to her/him. She/he tries to follow the customs handed down by her/his religion or her/his family.",
        "subscale": "conformity-obedience",
        "subscale2": "conformity-obedience",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 22,
        "desc": "Generally speaking would you say that most people can be trusted or that you can't be too careful in dealing with people?",
        "subscale": "trust",
        "subscale2": "trust",
        "reverse": 0,
        "min": 0,
        "max": 10,
        "min_label": "you can't be too careful",
        "max_label": "most people can be trusted"
    },
    {
        "q": 23,
        "desc": "Do you think that most people would try to take advantage of you if they got the chance, or would they try to be fair?",
        "subscale": "fairness",
        "subscale2": "fairness",
        "reverse": 0,
        "min": 0,
        "max": 10,
        "min_label": "most people would try to take advantage of me",
        "max_label": "most people would try to be fair"
    },
    {
        "q": 24,
        "desc": "She/he think it's important not to ask for more than what you have. She/he believes that people should be satisfied with what they have.",
        "subscale": "tradition",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    },
    {
        "q": 25,
        "desc": "Religious belief is important to her/him. She/he tries hard to do what her/his religion requires.",
        "subscale": "tradition",
        "subscale2": "None",
        "reverse": 1,
        "min": 1,
        "max": 6,
        "min_label": "very much like me",
        "max_label": "not at all like me"
    }
];